;+
; Test to save SDT data to CDF.
;-

ifn = shomedir()+'/po_sdt_fld_1998_0925_v01.sdt'
sdt = ssdtread(ifn)

ofn = shomedir()+'/po_sdt_fld_1998_0925_v01.cdf'
ginfo = {$
    title: 'Polar E field data',$
    text: 'Generated by Sheng Tian at the University of Minnesota'}
if file_test(ofn) then file_delete, ofn
scdfwrite, ofn, gattribute=ginfo


ut_e_inst = sdt.var.polar_e_spc_z.depend_0
e_inst = [[sdt.var.polar_e_spc_x_y.value],[sdt.var.polar_e_spc_56.value],[sdt.var.polar_e_spc_z.value]]

scdfwrite, ofn, 'ut_e_inst', value=ut_e_inst, cdftype='CDF_DOUBLE'
scdfwrite, ofn, 'e_inst', value=transpose(e_inst), dimensions=[3], dimvary=[1]

ut_b_inst = sdt.var.polar_b_spc_z.depend_0
b_inst = [[sdt.var.polar_b_spc_x_y.value],[sdt.var.polar_b_spc_56.value],[sdt.var.polar_b_spc_z.value]]
scdfwrite, ofn, 'ut_b_inst', value=ut_b_inst, cdftype='CDF_DOUBLE'
scdfwrite, ofn, 'b_inst', value=transpose(b_inst), dimensions=[3], dimvary=[1]

end