;+
; Save tplot vars to a given CDF file.
;
; vars. A string or array of tplot vars. Must depend on the same time.
; time_var=. The var name to save the time in the CDF file.
; istp=. A boolean, set to save time as epoch, otherwise unix time.
; filename=. A string for the CDF file.
;-

pro stplot2cdf, vars, time_var=time_var, istp=istp, filename=cdf_file

    if n_elements(vars) eq 0 then message, 'No vars ...'
    ;if n_elements(time_var) eq 0 then message, 'No time_var ...'
    if n_elements(time_var) eq 0 then time_var = 'unix_time'
    if file_test(cdf_file) eq 0 then cdf_save_setting, dictionary('Description', 'Autogenerated from stplot2cdf'), filename=cdf_file

    if ~cdf_has_var(time_var, filename=cdf_file) then begin
        get_data, vars[0], times
        if keyword_set(istp) then begin
            times = stoepoch(times,'unix')
            time_var_settings = dictionary($
                'VAR_TYPE', 'support_data', $
                'UNITS', 'msec', $
                'time_var_type', 'epoch' )
            cdf_save_var, time_var, value=times, filename=cdf_file, cdf_type='CDF_EPOCH'
        endif else begin
            time_var_settings = dictionary($
                'var_type', 'support_data', $
                'unit', 'sec', $
                'time_var_type', 'unix' )
            cdf_save_var, time_var, value=times, filename=cdf_file
        endelse
        cdf_save_setting, time_var_settings, filename=cdf_file, varname=time_var
    endif

    foreach var, vars do begin
        data = get_var_data(var, vals, limits=limits)
        cdf_save_var, var, value=data, filename=cdf_file
        settings = (isa(limits,'struct'))? dictionary(limits): dictionary()
        key = 'ylog'
        if settings.haskey(key) then begin
            ylog = settings[key]
        endif else ylog = 0
        
        if keyword_set(istp) then begin
            settings['DEPEND_0'] = time_var
            settings['VAR_TYPE'] = 'data'
            
            ; unit.
            key = 'unit'
            if settings.haskey(key) then begin
                settings['UNITS'] = settings[key]
                settings.remove, key
            endif
            foreach key, settings.keys() do if n_elements(settings[key]) gt 1 then settings.remove, key
            
            ; spec.
            key = 'spec'
            if settings.haskey(key) then begin
                if settings[key] eq 1 then settings['DISPLAY_TYPE'] = 'spectrogram'
            endif
            
            ; ylog.
            if ylog eq 1 then begin
                settings['SCALETYP'] = 'log'
            endif
        endif else begin
            settings['depend_0'] = time_var
            settings['var_type'] = 'data'
        endelse
        cdf_save_setting, settings, filename=cdf_file, varname=var
        
        ; Save depend_1
        if n_elements(vals) ne 0 then begin
            dep_var = var+'_depend_1'
            dep_settings = dictionary()
            cdf_save_var, dep_var, value=vals, filename=cdf_file
            if keyword_set(istp) then begin
                dep_settings['VAR_TYPE'] = 'meta_data'
                foreach key, dep_settings.keys() do if n_elements(dep_settings[key]) gt 1 then dep_settings.remove, key
                if ylog eq 1 then dep_settings['SCALETYP'] = 'log'
            endif else begin
                dep_settings['var_type'] = 'meta_data'
            endelse
            cdf_save_setting, dep_settings, filename=cdf_file, varname=dep_var
            if keyword_set(istp) then begin
                dep1_settings = dictionary('DEPEND_1',dep_var)
            endif else begin
                dep1_settings = dictionary('depend_1',dep_var)
            endelse
            cdf_save_setting, dep1_settings, filename=cdf_file, varname=var
        endif
    endforeach

end
